name: Deploy to S3

on:
  push:
    branches:
      - jekyll  # Trigger deployment on push to the jekyll branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify your Ruby version here

    - name: Install Bundler 2.5.11
      run: gem install bundler:2.5.11

    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Dependencies
      run: |
        cd NRG-ENGR-jekyll
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Build Jekyll site

      run: |
        cd NRG-ENGR-jekyll
        bundle exec jekyll build

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Sync files to S3
      run: |
        aws s3 sync ./_site/ s3://nrg-engr.blog --region ${{ secrets.AWS_REGION }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
